# Notebook 02 — Fundamentos de NumPy

## 🎯 Objetivos

Ao final deste notebook, você será capaz de:

- diferenciar escalar, vetor, matriz e tensor;
- interpretar `ndim` e `shape`;
- organizar exemplos e características em uma matriz de dados.

> **Como estudar:** execute as células na ordem. Leia a explicação antes de cada bloco e compare os resultados obtidos com a interpretação apresentada.


## 1. Importação

Por convenção, importamos NumPy como `np`. Todos os exemplos deste notebook usarão arrays NumPy.


In [1]:
import numpy as np

## 2. Escalar, vetor, matriz e tensor

- **Escalar:** um único valor, sem eixos;
- **Vetor:** uma sequência em um eixo;
- **Matriz:** linhas e colunas;
- **Tensor:** termo geral para arrays com qualquer número de eixos.

No contexto de Deep Learning, “tensor” também é usado de forma ampla para representar os dados processados pela rede.


In [2]:
escalar = np.array(5)

vetor = np.array([1, 2, 3])

matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

tensor = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

### Visualizando os valores

A impressão permite observar como o NumPy representa cada estrutura. Os colchetes aninhados indicam o número de eixos.


In [3]:
print("Escalar:")
print(escalar)

print("\nVetor:")
print(vetor)

print("\nMatriz:")
print(matriz)

print("\nTensor:")
print(tensor)

Escalar:
5

Vetor:
[1 2 3]

Matriz:
[[1 2 3]
 [4 5 6]]

Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 3. Número de dimensões com `ndim`

`ndim` informa quantos eixos o array possui. Isso não é a mesma coisa que a quantidade total de elementos.


In [4]:
print("Dimensão do escalar:", escalar.ndim)
print("Dimensão do vetor:", vetor.ndim)
print("Dimensão da matriz:", matriz.ndim)
print("Dimensão do tensor:", tensor.ndim)

Dimensão do escalar: 0
Dimensão do vetor: 1
Dimensão da matriz: 2
Dimensão do tensor: 3


## 4. Formato com `shape`

`shape` informa o tamanho de cada eixo. Exemplos:

- `(3,)`: vetor com três elementos;
- `(2, 3)`: matriz com duas linhas e três colunas;
- `(2, 2, 2)`: tensor com três eixos, cada um de tamanho dois.


In [5]:
print("Shape do escalar:", escalar.shape)
print("Shape do vetor:", vetor.shape)
print("Shape da matriz:", matriz.shape)
print("Shape do tensor:", tensor.shape)

Shape do escalar: ()
Shape do vetor: (3,)
Shape da matriz: (2, 3)
Shape do tensor: (2, 2, 2)


## 5. Representando um dataset

Cada linha representará uma pessoa e cada coluna uma característica. Podemos interpretar as colunas como idade, renda e quantidade de dependentes.


In [6]:
dados = np.array([
    [25, 3000, 2],
    [30, 5000, 5],
    [22, 2000, 1],
    [40, 7000, 10]
])

print(dados)
print("Shape:", dados.shape)

[[  25 3000    2]
 [  30 5000    5]
 [  22 2000    1]
 [  40 7000   10]]
Shape: (4, 3)


### Exemplos e características

Em Machine Learning, uma matriz de entrada costuma seguir o formato:

`(número de exemplos, número de características)`

Assim, `shape[0]` acessa as linhas e `shape[1]` acessa as colunas.


In [7]:
print("Número de exemplos:", dados.shape[0])
print("Número de características:", dados.shape[1])

Número de exemplos: 4
Número de características: 3


## 6. Revisão integrada

O bloco abaixo reúne a criação, a impressão e a interpretação do dataset. Ele repete parte do exemplo anterior de propósito, funcionando como uma revisão executável.


In [8]:
dados = np.array([
    [25, 3000, 2],
    [30, 5000, 5],
    [22, 2000, 1],
    [40, 7000, 10]
])

print("Dados:")
print(dados)

print("Shape:", dados.shape)

print("Número de exemplos:", dados.shape[0])
print("Número de características:", dados.shape[1])

Dados:
[[  25 3000    2]
 [  30 5000    5]
 [  22 2000    1]
 [  40 7000   10]]
Shape: (4, 3)
Número de exemplos: 4
Número de características: 3


## 🧠 Conclusão

Neste notebook, aprendemos a ler o formato dos dados antes de realizar qualquer cálculo. Essa habilidade evita erros de incompatibilidade dimensional em redes neurais.

### Exercícios

1. Crie uma matriz com 5 exemplos e 4 características.
2. Imprima `ndim`, `shape` e o número total de elementos com `.size`.
3. Crie um tensor que represente 2 imagens em escala de cinza com tamanho 3 × 3.

### Próximo notebook

No Notebook 03, usaremos essas estruturas em operações matemáticas e construiremos uma camada com vários neurônios.
